-- 코드를 입력하세요
SELECT USER_ID, PRODUCT_ID FROM ONLINE_SALE
GROUP BY USER_ID, PRODUCT_ID
HAVING COUNT(*)>1
ORDER BY USER_ID ASC, PRODUCT_ID DESC;
-- 그룹화한 대상에 대해서 HAVING으로 조건 작성. 
-- HAVING COUNT(*)>1은 각 그룹에서의 행 수가 1보다 큰 경우를 보여줌.
