-- 코드를 입력하세요
-- SELECT ANIMAL_ID, NAME
-- FROM ANIMAL_INS
-- WHERE NOT EXISTS(
--         SELECT 1
--         FROM ANIMAL_OUTS
-- );
SELECT ANIMAL_ID, NAME
FROM ANIMAL_OUTS

MINUS

SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS;