-- NOT EXISTS -> 순서 유의
-- SELECT ANIMAL_ID, NAME
-- FROM ANIMAL_OUTS A
-- WHERE NOT EXISTS (
--         SELECT 1
--         FROM ANIMAL_INS
--         WHERE ANIMAL_ID = A.ANIMAL_ID
-- )
-- ORDER BY ANIMAL_ID;

-- MINUS 쓰는 방법
-- SELECT ANIMAL_ID, NAME
-- FROM ANIMAL_OUTS

-- MINUS

-- SELECT ANIMAL_ID, NAME
-- FROM ANIMAL_INS

-- ORDER BY ANIMAL_ID;


-- LEFT OUTER JOIN + IS NULL 쓰는 방법

SELECT A.ANIMAL_ID, A.NAME
  FROM ANIMAL_OUTS A LEFT OUTER JOIN ANIMAL_INS B 
    ON (A.ANIMAL_ID = B.ANIMAL_ID )
 WHERE B.ANIMAL_ID IS NULL
 ORDER BY A.ANIMAL_ID;