-- 코드를 입력하세요
SELECT A.PRODUCT_ID, A.PRODUCT_NAME, A.PRICE*SUM(B.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT A JOIN FOOD_ORDER B ON (A.PRODUCT_ID = B.PRODUCT_ID)
WHERE TO_CHAR(B.PRODUCE_DATE, 'YYYY-MM') = '2022-05'
GROUP BY A.PRODUCT_ID, A.PRODUCT_NAME, A.PRICE
ORDER BY TOTAL_SALES DESC, A.PRODUCT_ID;