-- 코드를 작성해주세요
SELECT YEAR(A.DIFFERENTIATION_DATE) AS YEAR
     , (MAX_VAL - A.SIZE_OF_COLONY) AS YEAR_DEV
     , A.ID
 FROM ECOLI_DATA A 
         LEFT OUTER JOIN (
             SELECT DATE_FORMAT(DIFFERENTIATION_DATE, '%Y') AS YEAR
                  , MAX(SIZE_OF_COLONY) AS MAX_VAL 
              FROM ECOLI_DATA 
              GROUP BY DATE_FORMAT(DIFFERENTIATION_DATE, '%Y')) B
   ON (DATE_FORMAT(A.DIFFERENTIATION_DATE, '%Y')=B.YEAR)
ORDER BY YEAR, YEAR_DEV;




